version: '3'
services:
  web:
    image: 563083427725.dkr.ecr.us-east-1.amazonaws.com/jenkins-cicd-yarn:latest
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: ec2-tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: web

